# Generated by Django 6.0.2 on 2026-02-06 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_remove_auditlog_valid_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditlog",
            name="valid_event_type",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("DELETE", "Delete"),
                    ("TAKEDOWN", "Takedown"),
                    ("UNTAKEDOWN", "Untakedown"),
                    ("PASSWORD_CHANGE", "Password Change"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "LOGIN",
                            "LOGOUT",
                            "DELETE",
                            "TAKEDOWN",
                            "UNTAKEDOWN",
                            "PASSWORD_CHANGE",
                        ],
                    )
                ),
                name="valid_event_type",
            ),
        ),
    ]
