# Generated by Django 6.0.5 on 2026-05-27 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_remove_auditlog_valid_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditlog",
            name="valid_event_type",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("DELETE", "Delete"),
                    ("TAKEDOWN", "Takedown"),
                    ("UNTAKEDOWN", "Untakedown"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_CHANGE_FAILED", "Password Change Failed"),
                    ("TWO_FACTOR_ENABLED", "Two-Factor Enabled"),
                    ("TWO_FACTOR_VERIFIED", "Two-Factor Verified"),
                    ("TWO_FACTOR_FAILED", "Two-Factor Failed"),
                    ("INFO", "Info"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "LOGIN",
                            "LOGIN_FAILED",
                            "LOGOUT",
                            "DELETE",
                            "TAKEDOWN",
                            "UNTAKEDOWN",
                            "PASSWORD_CHANGE",
                            "PASSWORD_CHANGE_FAILED",
                            "TWO_FACTOR_ENABLED",
                            "TWO_FACTOR_VERIFIED",
                            "TWO_FACTOR_FAILED",
                            "INFO",
                        ],
                    )
                ),
                name="valid_event_type",
            ),
        ),
    ]
