# Generated by Django 6.0.5 on 2026-05-30 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_remove_auditlog_valid_event_type_auditlog_ip_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditlog",
            name="valid_event_type",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("DELETE", "Delete"),
                    ("TAKEDOWN", "Takedown"),
                    ("UNTAKEDOWN", "Untakedown"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_CHANGE_FAILED", "Password Change Failed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("TWO_FACTOR_ENABLED", "Two-Factor Enabled"),
                    ("TWO_FACTOR_VERIFIED", "Two-Factor Verified"),
                    ("TWO_FACTOR_FAILED", "Two-Factor Failed"),
                    ("INFO", "Info"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "LOGIN",
                            "LOGIN_FAILED",
                            "LOGOUT",
                            "DELETE",
                            "TAKEDOWN",
                            "UNTAKEDOWN",
                            "PASSWORD_CHANGE",
                            "PASSWORD_CHANGE_FAILED",
                            "PASSWORD_RESET",
                            "PASSWORD_RESET_FAILED",
                            "TWO_FACTOR_ENABLED",
                            "TWO_FACTOR_VERIFIED",
                            "TWO_FACTOR_FAILED",
                            "INFO",
                        ],
                    )
                ),
                name="valid_event_type",
            ),
        ),
    ]
